version: "3.9"

services:
  database:
    image: postgres
    container_name: games_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=gamestore
    volumes:
      - pgdata:/data/postgres

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file: ./backend/.env.production
    tty: true

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - "5173:5173"
    tty: true

volumes:
  pgdata:
    driver: local
